// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    baseUrl: 'app/lib',
    shim: {
      'backbone': {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      },
      'underscore': {
        deps: ['jquery'],
        exports: '_'
      }
    },
    paths: {
      model: '../js/models'
    }
  });

  define(["backbone", "underscore", "jquery"], function(Backbone, _, $) {
    var ChatView;
    return ChatView = Backbone.View.extend({
      el: $('#chat-view'),
      initialize: function(collection) {
        this.chat = collection;
        _.bindAll(this, 'render');
        this.chat.bind('add', this.render);
      },
      render: function() {
        var post, _i, _len, _ref;
        $(this.el).html('');
        _ref = this.chat.models;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          post = _ref[_i];
          $(this.el).append("<li>" + (post.get("text")) + "<span class='timestamp'>" + (post.get("time")) + "</span></li>");
        }
        return this;
      }
    });
  });

}).call(this);
