// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    baseUrl: 'app/lib',
    shim: {
      'backbone': {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      },
      'underscore': {
        deps: ['jquery'],
        exports: '_'
      }
    },
    paths: {
      model: '../js/models'
    }
  });

  define(["backbone", "underscore", "jquery", "model/post"], function(Backbone, _, $, Post) {
    var ChatInput;
    return ChatInput = Backbone.View.extend({
      events: {
        'click': 'submit'
      },
      initialize: function(submit_id, input_id, collection) {
        this.submit_id = submit_id;
        this.input_id = input_id;
        this.chat = collection;
        this.setElement($('#' + this.submit_id));
        _.bindAll(this, 'submit');
        return $('#' + this.input_id).focus().select();
      },
      submit: function(e) {
        var post;
        e.preventDefault();
        post = new Post($('#' + this.input_id).val(), new Date());
        this.chat.add(post);
        post.save();
        return $('#' + this.input_id).val('');
      }
    });
  });

}).call(this);
