// Generated by CoffeeScript 1.3.3
(function() {

  require(["libs/jquery-1.7.2.min", "libs/underscore-min", "libs/backbone-min"], function() {
    var $;
    $ = jQuery;
    return $(function() {
      var ListView, listView;
      ListView = Backbone.View.extend({
        el: $('body'),
        initialize: function() {
          _.bindAll(this, 'render');
          return this.render();
        },
        render: function() {
          return $(this.el).append("<ul id='main-list'> <li>hello world</li><ul>");
        }
      });
      return listView = new ListView();
    });
  });

}).call(this);
