// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    baseUrl: 'app/lib',
    shim: {
      'backbone': {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      },
      'underscore': {
        deps: ['jquery'],
        exports: '_'
      }
    },
    paths: {
      js: '../js',
      model: '../js/models',
      view: '../js/views'
    }
  });

  requirejs(["backbone", "underscore", "jquery", "model/post", "view/chatInput", "view/chatView"], function(Backbone, _, $, Post, ChatInput, ChatView) {
    var app;
    app = function($) {
      var Chat, chat, chatInput, chatView, chatlog;
      Chat = Backbone.Collection.extend({
        model: Post
      });
      chat = new Chat();
      chatlog = '';
      $.get('/chat', function(data) {
        var hash, post, _i, _len, _results;
        data = data.split('}');
        data.pop();
        _results = [];
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          hash = data[_i];
          hash = JSON.parse(hash + '}');
          post = new Post(hash.text, hash.time);
          _results.push(chat.add(post));
        }
        return _results;
      });
      chatView = new ChatView(chat);
      return chatInput = new ChatInput("chat-submit", "chat-input", chat);
    };
    return app(jQuery);
  });

}).call(this);
