// Generated by CoffeeScript 1.3.3
(function() {

  requirejs.config({
    baseUrl: 'app/lib',
    shim: {
      'backbone': {
        deps: ['underscore', 'jquery'],
        exports: 'Backbone'
      },
      'underscore': {
        deps: ['jquery'],
        exports: '_'
      }
    }
  });

  define(["backbone", "underscore", "jquery"], function(Backbone, _, $) {
    var Post;
    return Post = Backbone.Model.extend({
      initialize: function(text, time) {
        this.set({
          text: text
        });
        this.set({
          time: time
        });
      },
      text: null,
      time: null,
      url: "/"
    });
  });

}).call(this);
